### ISSUE TITLE
boards/STM32F746IGT6-WaveShare-Core7XXI.md: headers spec fix

### ISSUE THREAD

**Issue by abelykh0** [STM32-base/STM32-base.github.io#10]
The headers on this board are 2x 2x40 male dupont (2mm), not 2x 2x27 male dupont (2.54mm)

https://www.waveshare.com/w/upload/7/76/Core746I-Schematic.pdf

Thank you! You have a great resource, I just want to improve it.

**Comment by ThomasGravekamp** [comment]
Oops, copy paste error. Feel free to make a pull request when you find things like this.

**Comment by abelykh0** [comment]
Sure, created pull request. Also removed serial which is not there.

**Comment by ThomasGravekamp** [comment]
Thanks for your contribution, I've merged the changes.
