### ISSUE TITLE
Add STM32F407ZET6 board

### ISSUE THREAD

**Issue by ostanki** [STM32-base/STM32-base.github.io#14]
Will make a draft for 
![IMG_20191127_005225488](https://user-images.githubusercontent.com/37983318/69693600-2cddca80-10d6-11ea-9823-580aa9943b32.jpg)

**Comment by ThomasGravekamp** [comment]
You will make a draft for this board? Or are you asking me to make a draft for this board?

**Comment by ostanki** [comment]
Sorry I didn't make myself quite clear. I will make the draft.

**Comment by ThomasGravekamp** [comment]
This one seems to be done. Closing this issue then. Thanks!
