### ISSUE TITLE
left navigation panel truncated and can't be scrolled

### ISSUE THREAD

**Issue by ag88** [STM32-base/STM32-base.github.io#19]
the left navigation panel is truncated if the (firefox) browser window is too small, smaller screens probably struggle with it.

this is likely due to the header stylesheet declaration header { position : fixed; }
https://github.com/STM32-base/STM32-base.github.io/blob/master/_sass/styles.scss#L20
```
header, footer {
    float: left;
//    position: fixed;
    width: 18rem;
    -webkit-font-smoothing: subpixel-antialiased;
}
```
commenting it probably resolve the issue

**Comment by ThomasGravekamp** [comment]
Thanks for reporting this issue. I was already aware of this.

I am currently working on a new layout that should solve this problem.

**Comment by ag88** [comment]
thanks ! :)

**Comment by ag88** [comment]
thanks ! :)
