### ISSUE TITLE
Suggestion: add STM32F411CEU6 board

### ISSUE THREAD

**Issue by abelykh0** [STM32-base/STM32-base.github.io#25]
Enhancement suggestion: add STM32F411CEU6 (see https://github.com/mcauser/WEACT_F411CEU6)

**Comment by ThomasGravekamp** [comment]
Thanks for opening this issue. I've already ordered these boards, and they lay here waiting to be added to the website.

I'm currently working my way through converting the existing board pages to JSON files so they can be generated from a template. I want to finish this first.

**Comment by ThomasGravekamp** [comment]
Fixed by commit a61f0d5355d8f9e4cb91299e17a5f7b73d5e56b6
