### ISSUE TITLE
STM32F103C8T6-Black_Board page issue

### ISSUE THREAD

**Issue by mzhboy** [STM32-base/STM32-base.github.io#32]
1. This board has HSE(8M) and LSE
2. [Original schematic](https://stm32-base.org/assets/pdf/boards/original-schematic-STM32F103C8T6_Black_Board.pdf) and [Original schematic](https://stm32-base.org/assets/img/boards/original-schematic_STM32F103C8T6_Black_Board.png) can't open(404)

**Comment by ThomasGravekamp** [comment]
Thanks for reporting these errors. I'll fix them.
