### ISSUE TITLE
Add STM32_F030 board

### ISSUE THREAD

**Issue by allenchak** [STM32-base/STM32-base.github.io#35]
Board Name: STM32_F030
Inputs, outputs, connectors & headers:

1. STM32F030F4P6
2. MicroUSB connector
3. SWD connector
4. P1
5. P2
6. LED: 2 (D1: Power LED; D2: User LED, PA4)

- D1: Power LED
- D2: User LED, PA4

7. Button: 2

- K1: User Button, PA0
- RST: NRST

8. Schematic included

![stm32f030_minimum_schematic](https://user-images.githubusercontent.com/7300880/102480398-2c2a2480-409b-11eb-9c0d-70df41c349ac.jpg)
![image1](https://user-images.githubusercontent.com/7300880/102480381-259bad00-409b-11eb-88c3-f344257cdd37.jpg)
![image2](https://user-images.githubusercontent.com/7300880/102480396-2af8f780-409b-11eb-8630-eb174aaafd36.jpg)
![image3](https://user-images.githubusercontent.com/7300880/102480397-2b918e00-409b-11eb-8d34-5dcfb31766bd.jpg)

**Comment by ThomasGravekamp** [comment]
Thanks for bringing this to my attention.

Did you take that first picture yourself? If so, would you be able to also take one of the back of the board and one that has a perspective view.

The pictures on stm32-base.org are licenced under the Creative Commons Attribution-NonCommercial 4.0 International (CC BY 4.0), so I can not randomly use someone's pictures. They'll have to agree to share them.

**Comment by allenchak** [comment]
Yes, the image1 was taken by me. Sure, I could take 2 more images to you, but I have a sticker on the backside, I try to remove it. Or else you do not mind?

**Comment by allenchak** [comment]
Unfortunately the stickers quite large, but lucky it does not cover any silkscreen.
Anyway, I will upload the image tomorrow. If you need the product link, just let me know.

**Comment by allenchak** [comment]
![Back](https://user-images.githubusercontent.com/7300880/102576232-03a03a00-4130-11eb-9fd7-9b2073372416.jpg)
![Perspective](https://user-images.githubusercontent.com/7300880/102576238-0733c100-4130-11eb-8ccc-ca1f29373935.jpg)

**Comment by ThomasGravekamp** [comment]
Thanks! I'll create a page for this board when I find the time for it somewhere the coming two weeks.

**Comment by martinstingl** [comment]
Please also add the schematic from the initial post to the board page, most STM32F030F4P6 seems to use it.

**Comment by ThomasGravekamp** [comment]
@martinstingl Can you please verify that the connections listed for the buttons and LEDs are correct? I looked at the schematic, but it looks like it is meant for another board.

**Comment by rfivet** [comment]
This is the droid you are looking for.
![STM32_F030_Schematics](https://user-images.githubusercontent.com/28284829/103449527-480d0780-4ce4-11eb-846b-9a5146f31ca2.png)

**Comment by martinstingl** [comment]
@ThomasGravekamp
You are right, I measured the connection on this board and there is a difference:
https://stm32-base.org/assets/img/boards/STM32F030F4P6_STM32F030_DEMO_BOARD_V1.1-2.jpg

- PA4 is connected directly to the LED, its anode is connected to 3V3 via 1k
- BOOT0 is pulled to 3V3 via 1k, and can be connected to GND or 3V3 with the 3 position jumper

- The reset button is connected unchanged

**Comment by ThomasGravekamp** [comment]
Thanks for verifying @martinstingl, looks like I've made no mistakes.
