### ISSUE TITLE
SongHe stm32f401CCU6 board

### ISSUE THREAD

**Issue by vsessink** [STM32-base/STM32-base.github.io#41]
Hoi Thomas, hi others, found a new board. Please see https://www.amazon.com/SongHe-STM32F401-Development-STM32F401CCU6-Learning/dp/B07XBWGF9M and https://www.electrodragon.com/product/stm32f401-mini-dev-board-stm32f401ccu6/ with more pictures.

The board is similar to Black Pills, but has a few differences: no user button; BOOT0 and BOOT1 are dip switches.

Even more information:
https://www.electrodragon.com/w/STM32F4
https://drive.google.com/file/d/1I3E_-ZKEtSfsHiNDR-I87v4AHSIqD978/view (schematics)
https://cntronic.com/stm32f401-development-board-stm32f401ccu6-stm32f4-learning-board-30332 (still more pictures)

The following pictures can be used under public domain, I made them and I'm donating them. I can make some more pictures with a neutral grey background if that is what you need.

@ThomasGravekamp ik heb een pull request geprobeerd, maar welke power regulator enz - ik weet het echt niet. Laat weten wat je nodig hebt. Geweldig project, trouwens!

![DSC01444](https://user-images.githubusercontent.com/2970510/112608000-1bb3e380-8e1a-11eb-9df3-3fb3a716cedf.JPG)
![DSC01445](https://user-images.githubusercontent.com/2970510/112608004-1d7da700-8e1a-11eb-834f-a45a0d16444d.JPG)

**Comment by ThomasGravekamp** [comment]
Hi, thank you for wanting to contribute!

I prefer having pictures with a grey background to keep them consistent, if that's not too much trouble. I take three pictures of each board: a perspective view (shown on the boards overview page), a top view, and a bottom view.

I'll have free some time to add this board page. By the way, the regulator used on this board is the XC6204: https://stm32-base.org/assets/pdf/regulators/XC6204-XC6205.pdf.

**Comment by vsessink** [comment]
![DSC01448](https://user-images.githubusercontent.com/2970510/116528202-d6cd1200-a8db-11eb-80f6-e0b3b68a750c.JPG)
![DSC01450](https://user-images.githubusercontent.com/2970510/116529356-29f39480-a8dd-11eb-99da-b5e619861b94.JPG)
![backDSC01453](https://user-images.githubusercontent.com/2970510/116529384-30820c00-a8dd-11eb-854c-93325a8f2967.JPG)

**Comment by ThomasGravekamp** [comment]
I've added the board page. Thanks for helping out with the images!
