### ISSUE TITLE
Schematic and Board views for STM32F407VGT6_STM32F4XX_M

### ISSUE THREAD

**Issue by maximvoven** [STM32-base/STM32-base.github.io#42]
Hello, I stumbled on the schematic and board files for the [STM32F407VGT6_STM32F4XX_M](https://stm32-base.org/boards/STM32F407VGT6-STM32F4XX-M)
Personally I don't know how to add this information to the website so therefore cannot create a pull request so i'm just going to put it here in the hopes that someone who better understand GitHub Pages and how this website is setup to add this to the website.
Also these files may be relevant to the VET6 varient of this board, but I cannot check (on quick visual inspection board view and image seem to match).

[original-dimensions-STM32F407VGT6_STM32F4XX_M.pdf](https://github.com/STM32-base/STM32-base.github.io/files/6488473/original-dimensions-STM32F407VGT6_STM32F4XX_M.pdf)
[original-schematic-STM32F407VGT6_STM32F4XX_M.pdf](https://github.com/STM32-base/STM32-base.github.io/files/6488474/original-schematic-STM32F407VGT6_STM32F4XX_M.pdf)

**Comment by ThomasGravekamp** [comment]
Thanks for bringing this to my attention. I've added the files.
