### ISSUE TITLE
Wrong SWD Pinout on website

### ISSUE THREAD

**Issue by maksoff** [STM32-base/STM32-base.github.io#43]
For Blue Pill, (STM32-base.github.io/_data/boards/STM32F103C8T6-Blue-Pill.json) in section "SWD header pins" should be:

- 3V3
- DIO (PA13)
- CLK (PA14)
- GND

**Comment by ThomasGravekamp** [comment]
Thanks for bringing this to my attention. I've fixed it.

**Comment by maksoff** [comment]
Thank you, great!
