### ISSUE TITLE
boards/STM32F746IGT6-WaveShare-Core7XXI.md: SDRAM is 8 Mb, not 64 Mb

### ISSUE THREAD

**Issue by abelykh0** [STM32-base/STM32-base.github.io#9]
For this board SDRAM is 8 Mb, not 64 Mb (see http://www.issi.com/WW/pdf/42-45S16400J.pdf). 64 MBit = 8 Mb

**Comment by ThomasGravekamp** [comment]
Thanks for submitting this issue.

I always thought that MB meant Megabyte and that Mb meant Megabit. I guess I got that from [data transfer rates](https://en.wikipedia.org/wiki/Data-rate_units), in which Mb seems to be used more commonly.

I will fix this.

**Comment by abelykh0** [comment]
Maybe you are right, however if you google "64 mbit in mb" it will show 8 "Megabyte"

**Comment by ThomasGravekamp** [comment]
If you want you can include the fix for this in your current PR. You may change the text to "64Mbit".

**Comment by abelykh0** [comment]
Let's keep it separate, thanks.

**Comment by abelykh0** [comment]
I would actually prefer to see 8 megabytes, but it is your site...

**Comment by ThomasGravekamp** [comment]
Hm, yeah, I can agree on that, to keep it consistent with the memory size units used for the microcontroller itself.

**Comment by ThomasGravekamp** [comment]
Done, thanks for your input.
